### ISSUE TITLE
DynDNS Authentication

### ISSUE THREAD

**Issue by darz82** [davispuh/DNSUpdater#3]
Hi,

Maybe you could help me.

1. I've started DNSUpdater using **updateDNS --serve http://192.168.1.2/** then when trying to authenticate the DynDNS URL e.g **http://192.168.1.2/nic/update?hostname=dyndns.example.com&myip=1.1.1.1** what username do I use? or do I need to set it somewhere? I've set the SharedSecret with a basic password but I'm not aware of any username option under the HTTP section

2. Is the SharedSecret option just a plain text password or does it need to be base64 or md5 encoded? 

cheers,

**Comment by davispuh** [comment]
Indeed looks like I haven't documented this.
Username is always `DNSUpdate`
And password you enter is base64 encoded HMAC-SHA256 of SharedSecret.
So basically if you use secret `test123`
Then password you'll use is
```ruby
$ ruby -r base64 -r openssl -e "puts Base64.urlsafe_encode64(OpenSSL::HMAC.digest('SHA256', 'test123', 'DNSUpdate'), padding: false)"
NuZ3zyuc_ageBumzQVrb4JSiurzUlHhCBJ8cVxnBtjg
```

Can see this in test https://github.com/davispuh/DNSUpdater/blob/master/spec/updaters/http_spec.rb#L82

**Comment by darz82** [comment]
Cool thanks for the info :) Gonna try and build a docker instance of the app ;)
