### ISSUE TITLE
Hey Dāvis, sorry to bother you, I am looking for an expert in PowerDNS/Ruby

### ISSUE THREAD

**Issue by tomschlenkhoff** [davispuh/DNSUpdater#8]
need someone to brainstorm (paid) for a few hours. Interested in a chat?
Cheers, Tom

**Comment by davispuh** [comment]
Hi,

There is pretty good documentation for PowerDNS so it shouldn't be too complicated.
I'm pretty busy, what it's about and what's the rate?

**Comment by tomschlenkhoff** [comment]
Hey, thanks. Have an email or other contact point? It‘s about designing a VPN-scalable filtering VPN-provider. What‘s your rate if you are available at all?

Auf meinem Gameboy getippt.

**Comment by davispuh** [comment]
That doesn't seem trivial. Would expect to take a while so I don't have time for that.
